name: CI Pipeline

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      # Lint and test CI/CD
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install client dependencies
        working-directory: client
        run: npm ci

      - name: Install server dependencies
        working-directory: server
        run: npm ci

      - name: Lint client
        working-directory: client
        run: npm run lint

      - name: Test client
        working-directory: client
        run: npm test

      - name: Test server
        working-directory: server
        run: npm test

      - name: Build client
        working-directory: client
        run: npm run build

      # Playwright CI/CD
      - name: Install Playwright browsers
        working-directory: client
        run: npx playwright install --with-deps

      - name: Run E2E tests
        working-directory: client
        run: npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 30

  # Deployment to Render
  deploy:
    needs: test_and_build
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}

    steps:
      - name: Deploy to Render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: curl "$RENDER_DEPLOY_HOOK"
